# name: docs

# on:
#   # 每当 push 到 main 分支时触发部署
#   push:
#     branches: [main]
#   # 手动触发部署
#   workflow_dispatch:

# jobs:
#   docs:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v3
#         with:
#           # “最近更新时间” 等 git 日志相关信息，需要拉取全部提交记录
#           fetch-depth: 0

#       - name: Setup pnpm
#         uses: pnpm/action-setup@v2
#         with:
#           # 选择要使用的 pnpm 版本
#           version: 8
#           # 使用 pnpm 安装依赖
#           run_install: true

#       - name: Setup Node.js
#         uses: actions/setup-node@v3
#         with:
#           # 选择要使用的 node 版本
#           node-version: 18
#           # 缓存 pnpm 依赖
#           cache: pnpm

#       # 运行构建脚本
#       - name: Build VuePress site
#         run: pnpm docs:build

#       # 查看 workflow 的文档来获取更多信息
#       # @see https://github.com/crazy-max/ghaction-github-pages
#       - name: Deploy to GitHub Pages
#         uses: crazy-max/ghaction-github-pages@v2
#         with:
#           # 部署到 gh-pages 分支
#           target_branch: gh-pages
#           # 部署目录为 VuePress 的默认输出目录
#           build_dir: docs/.vuepress/dist
#         env:
#           # @see https://docs.github.com/cn/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
#           GITHUB_TOKEN: ${{ secrets.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 }}


name: Build and Deploy to github & gitee
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 构建Node环境
      - name: Build Node.js Env
        uses: actions/setup-node@v1
        with:
          node-version: '16'
      # 检出main分支代码
      - name: Checkout Code
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      # 安装依赖
      - name: Install dependencies
        run: npm install 
      # 项目打包
      - name: Build Project 
        run: npm run build
      # github 部署分支gh-pages 到github pages
      - name: Deploy dist on gh-pages
        uses: JamesIves/github-pages-deploy-action@4.2.0
        with:
          # BRANCH: gh-pages
          # FOLDER: dist
          ACCESS_TOKEN: ${{ secrets.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 }}
          # 部署到 gh-pages 分支
          target_branch: gh-pages
          # 部署目录为 VuePress 的默认输出目录
          build_dir: docs/.vuepress/dist 
      # # 同步github代码到gitee
      # - name: Sync to Gitee
      #   uses: wearerequired/git-mirror-action@master
      #   env:
      #     # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
      #     SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
      #   with:
      #     # 注意替换为你的 GitHub 源仓库地址
      #     source-repo: git@github.com:AnyFork/blog-docs.git
      #     # 注意替换为你的 Gitee 目标仓库地址
      #     destination-repo: git@gitee.com:AnyFork/blog-docs.git

      # # 自动部署gitee gh-pages分支
      # - name: Build Gitee Pages
      #   uses: yanglbme/gitee-pages-action@main
      #   with:
      #     # 注意替换为你的 Gitee 用户名
      #     gitee-username: 874957743@qq.com
      #     # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
      #     gitee-password: ${{ secrets.GITEE_PASSWORD }}
      #     # 注意替换为你的 Gitee 仓库，仓库名严格区分大小写，请准确填写，否则会出错
      #     gitee-repo: AnyFork/blog-docs
      #     # 要部署的分支，默认是 master，若是其他分支，则需要指定（指定的分支必须存在）
      #     branch: gh-pages
